name: Build

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release --locked
      - name: Archive build
        uses: actions/upload-artifacts@v2
        with:
          name: discord-bot
          path: target/release/discord-bot
